# Generated by Django 5.1.7 on 2025-04-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedflight',
            name='flight_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedflight',
            name='flight_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedflight',
            name='pic_path',
            field=models.CharField(max_length=100),
        ),
    ]
