on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_flight_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set AWS Region
        run: echo "AWS_REGION=eu-west-2" >> $GITHUB_ENV

      - name: Run find_my_flight script
        run: |
          export PYTHONPATH=$(pwd)
          export AWS_REGION=eu-west-2
          python src/find_my_flight.py
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update: ran find_my_flight script"
          git push
